environment:
  # Python version used
  MICROPY_CPYTHON3: c:/python34/python.exe

init:
  # Set build version number to commit to be travis-like
- ps: Update-AppveyorBuild -Version $env:appveyor_repo_commit.substring(0,8)

configuration:
- Debug
- Release

platform:
- x86
- x64

build:
  project: ports/windows/micropython.vcxproj
  verbosity: normal

test_script:
- cmd: >-
    cd tests

    %MICROPY_CPYTHON3% run-tests

skip_tags: true

deploy: off

nuget:
  disable_publish_on_pr: true
